server {
    listen 80;
    listen [::]:80;
    server_name lamimi.id www.lamimi.id; # Ganti dengan domain Anda atau IP jika belum pakai domain

    client_max_body_size 10M;

    # Lokasi tantangan verifikasi SSL Let's Encrypt / Certbot
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Reverse proxy ke API FastAPI Container
    location /api/ {
        proxy_pass http://backend:8001;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Serve file upload (cover & ebook/bukti bayar) langsung dari volume
    location /uploads/ {
        alias /var/www/uploads/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Reverse proxy ke Frontend React Container
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}